In [2]:
import pandas as pd
from pathlib import Path


def parse_rater(rater_id) -> tuple[int, int]:
    """
    Decode a Rater ID of form ±TTPPPPP into (team, person).

    Examples
    --------
    >>> parse_rater(-100001)   # team 1, person 1
    (1, 1)
    >>> parse_rater(-2500005)  # team 25, person 5
    (25, 5)
    """
    if pd.isna(rater_id):
        return (None, None)
    a = abs(int(rater_id))
    team   = a // 100_000
    person = a % 10
    return team, person


def load_with_rater(path: str | Path, sheet: str = "By Rater") -> pd.DataFrame:
    """Load a snapshot file (csv or xlsx) and add team + person columns."""
    path = Path(path)
    if path.suffix == ".csv":
        df = pd.read_csv(path, header=1)
    else:
        df = pd.read_excel(path, sheet_name=sheet, header=1)

    # First column is Rater but usually reads as 'Unnamed: 0'
    df = df.rename(columns={df.columns[0]: "Rater"})
    df = df[pd.notna(df["Rater"])].copy()
    df["Rater"] = df["Rater"].astype(int)

    decoded = df["Rater"].apply(parse_rater)
    df["team"]   = [t for t, _ in decoded]
    df["person"] = [p for _, p in decoded]
    return df

In [ ]:
df_1 = load_with_rater("/content/drive/MyDrive/Synthetic_data/SYNTHETIC #1 - Post Challenge choice.xlsx")
df_1.head()

In [ ]:
output_path = '/content/drive/MyDrive/Synthetic_data/synthetic_data_1.csv'
df_1.to_csv(output_path, index=False)
print(f"DataFrame saved to: {output_path}")

DataFrame saved to: /content/drive/MyDrive/Synthetic_data/synthetic_data_1.csv

In [ ]:
df_2 = load_with_rater("/content/drive/MyDrive/Synthetic_data/SYNTHETIC #2 - End of Day 1.xlsx")
df_2.head()

,Rater,Wellbeing,Team Access,Productivity,Unnamed: 4,<b>Capacity</b> of the team,<b>Capability</b> of the team,<b>Priorities</b> of the team,<b>Collaboration</b> within the team,Ability to challenge decisions and actions <b>safely</b>,...,<b>Leadership</b> of the team,Unnamed: 12,How well our <b>solution</b> meets the objectives of the challenge,How innovative are we being in our use of <b>technology</b>,How <b>ambitious</b> are we with our solution,Unnamed: 16,Unnamed: 17,Unnamed: 18,team,person
0,-100001,41,42,72,NaN,42,43,50,71,47,...,60,NaN,53,51,54,NaN,NaN,NaN,1,1
1,-100002,44,42,45,NaN,44,34,18,38,31,...,49,NaN,41,36,37,NaN,NaN,NaN,1,2
2,-100003,53,29,46,NaN,58,39,50,40,59,...,56,NaN,49,51,42,NaN,NaN,NaN,1,3
3,-100004,56,49,51,NaN,46,64,58,50,66,...,45,NaN,57,58,60,NaN,NaN,NaN,1,4
4,-100005,16,39,58,NaN,26,46,32,31,32,...,42,NaN,41,47,39,NaN,NaN,NaN,1,5

In [ ]:
output_path = '/content/drive/MyDrive/Synthetic_data/synthetic_data_2.csv'
df_2.to_csv(output_path, index=False)
print(f"DataFrame saved to: {output_path}")

DataFrame saved to: /content/drive/MyDrive/Synthetic_data/synthetic_data_2.csv

In [ ]:
df_3 = load_with_rater("/content/drive/MyDrive/Synthetic_data/SYNTHETIC #3 - Start of Day 2.xlsx")
df_3.head()

,Rater,Wellbeing,Team Access,Productivity,Unnamed: 4,<b>Capacity</b> of the team,<b>Capability</b> of the team,<b>Priorities</b> of the team,<b>Collaboration</b> within the team,Ability to challenge decisions and actions <b>safely</b>,...,How well our <b>solution</b> meets the objectives of the challenge,How innovative are we being in our use of <b>technology</b>,How <b>ambitious</b> are we with our solution,What is the <b>commercial application</b> of our solution,How <b>beneficial</b> is our solution,Unnamed: 18,Unnamed: 19,Unnamed: 20,team,person
0,-100001,44,54,52,NaN,61,56,43,57,45,...,37,61,43,49,62,NaN,NaN,NaN,1,1
1,-100002,51,35,50,NaN,57,38,43,39,42,...,34,40,38,41,31,NaN,NaN,NaN,1,2
2,-100003,42,42,48,NaN,30,56,42,43,52,...,57,44,53,46,55,NaN,NaN,NaN,1,3
3,-100004,64,64,35,NaN,53,62,67,46,56,...,57,78,76,32,47,NaN,NaN,NaN,1,4
4,-100005,33,45,48,NaN,34,29,39,53,62,...,35,50,46,47,66,NaN,NaN,NaN,1,5

In [ ]:
output_path = '/content/drive/MyDrive/Synthetic_data/synthetic_data_3.csv'
df_3.to_csv(output_path, index=False)
print(f"DataFrame saved to: {output_path}")

DataFrame saved to: /content/drive/MyDrive/Synthetic_data/synthetic_data_3.csv

In [ ]:
df_4 = load_with_rater("/content/drive/MyDrive/Synthetic_data/SYNTHETIC #4 - Mid Day 2.xlsx")
df_4.head()

,Rater,Wellbeing,Team Access,Productivity,Unnamed: 4,<b>Capacity</b> of the team,<b>Capability</b> of the team,<b>Priorities</b> of the team,<b>Collaboration</b> within the team,Ability to challenge decisions and actions <b>safely</b>,...,How well our <b>solution</b> meets the objectives of the challenge,How innovative are we being in our use of <b>technology</b>,How <b>ambitious</b> are we with our solution,What is the <b>commercial application</b> of our solution,How <b>beneficial</b> is our solution,Unnamed: 18,Unnamed: 19,Unnamed: 20,team,person
0,-100001,52,38,55,NaN,52,34,63,63,67,...,40,53,61,45,45,NaN,NaN,NaN,1,1
1,-100002,58,32,44,NaN,45,45,52,52,42,...,58,46,54,47,57,NaN,NaN,NaN,1,2
2,-100003,52,52,64,NaN,50,59,56,56,49,...,51,62,54,43,46,NaN,NaN,NaN,1,3
3,-100004,54,60,39,NaN,35,67,69,69,74,...,51,65,53,58,61,NaN,NaN,NaN,1,4
4,-100005,57,44,43,NaN,49,48,42,42,55,...,45,44,33,50,52,NaN,NaN,NaN,1,5

In [ ]:
output_path = '/content/drive/MyDrive/Synthetic_data/synthetic_data_4.csv'
df_4.to_csv(output_path, index=False)
print(f"DataFrame saved to: {output_path}")

DataFrame saved to: /content/drive/MyDrive/Synthetic_data/synthetic_data_4.csv

In [ ]:
df_5 = load_with_rater("/content/drive/MyDrive/Synthetic_data/SYNTHETIC #5 - End of Day 2.xlsx")
df_5.head()

,Rater,Wellbeing,Team Access,Productivity,Unnamed: 4,<b>Capacity</b> of the team,<b>Capability</b> of the team,<b>Priorities</b> of the team,<b>Collaboration</b> within the team,Ability to challenge decisions and actions <b>safely</b>,...,How well have we <b>presented </b>our solution,Unnamed: 19,HCD helped me to contribute more,HCD helped our team understand how we were really working together,The insights from the HCD influenced the way our team approached the challenge,Unnamed: 23,Unnamed: 24,Unnamed: 25,team,person
0,-100001,59,22,20,NaN,45,38,37,37,48,...,47,NaN,44,40,40,NaN,NaN,NaN,1,1
1,-100002,52,38,39,NaN,43,27,27,27,26,...,35,NaN,43,11,11,NaN,NaN,NaN,1,2
2,-100003,27,37,38,NaN,73,44,57,57,51,...,50,NaN,40,41,41,NaN,NaN,NaN,1,3
3,-100004,39,30,48,NaN,54,72,59,59,44,...,55,NaN,36,46,46,NaN,NaN,NaN,1,4
4,-100005,65,36,42,NaN,50,24,27,27,30,...,41,NaN,27,40,40,NaN,NaN,NaN,1,5

In [ ]:
output_path = '/content/drive/MyDrive/Synthetic_data/synthetic_data_5.csv'
df_5.to_csv(output_path, index=False)
print(f"DataFrame saved to: {output_path}")

DataFrame saved to: /content/drive/MyDrive/Synthetic_data/synthetic_data_5.csv

In [ ]:
df_survey_1 = load_with_rater("/content/drive/MyDrive/Real_data/Survey 1 Raw Data.xlsx")
df_survey_1.head()

,Rater,Wellbeing,Team Access,Productivity,Balance,Unnamed: 5,Personal Style,Preferred Working Culture,Unnamed: 8,Unnamed: 9,...,Level of <b>anxiety</b> towards AI,Level of <b>knowledge</b> of AI,<b>Business usage</b> of AI,Level of <b>training</b> and support received wrt AI,Opportunity to <b>experiment </b>and innovate with AI,<b>Importance</b> to you in your career,Unnamed: 23,Unnamed: 24,team,person
0,-1700002,63,48,31,36,NaN,35,48,68.0,67,...,40,30,33,52,34.0,72,NaN,Male,17,2
1,-1700000,40,54,67,49,NaN,64,57,76.0,50,...,16,84,90,88,94.0,92,NaN,Male,17,0
2,-2300004,44,48,52,56,NaN,48,48,52.0,52,...,40,44,48,52,56.0,60,NaN,Male,23,4
3,-2300003,86,75,80,50,NaN,75,78,87.0,87,...,67,77,77,81,90.0,83,NaN,Male,23,3
4,-400002,61,65,34,49,NaN,40,17,56.0,42,...,73,67,76,64,30.0,52,NaN,Male,4,2

In [ ]:
output_path = '/content/drive/MyDrive/Real_data/real_data_1.csv'
df_survey_1.to_csv(output_path, index=False)
print(f"DataFrame saved to: {output_path}")

DataFrame saved to: /content/drive/MyDrive/Real_data/real_data_1.csv

In [ ]:
df_survey_2 = load_with_rater("/content/drive/MyDrive/Real_data/Survey 1 Raw Data.xlsx")
df_survey_2.head()

,Rater,Wellbeing,Team Access,Productivity,Balance,Unnamed: 5,Personal Style,Preferred Working Culture,Unnamed: 8,Unnamed: 9,...,Level of <b>anxiety</b> towards AI,Level of <b>knowledge</b> of AI,<b>Business usage</b> of AI,Level of <b>training</b> and support received wrt AI,Opportunity to <b>experiment </b>and innovate with AI,<b>Importance</b> to you in your career,Unnamed: 23,Unnamed: 24,team,person
0,-1700002,63,48,31,36,NaN,35,48,68.0,67,...,40,30,33,52,34.0,72,NaN,Male,17,2
1,-1700000,40,54,67,49,NaN,64,57,76.0,50,...,16,84,90,88,94.0,92,NaN,Male,17,0
2,-2300004,44,48,52,56,NaN,48,48,52.0,52,...,40,44,48,52,56.0,60,NaN,Male,23,4
3,-2300003,86,75,80,50,NaN,75,78,87.0,87,...,67,77,77,81,90.0,83,NaN,Male,23,3
4,-400002,61,65,34,49,NaN,40,17,56.0,42,...,73,67,76,64,30.0,52,NaN,Male,4,2

In [ ]:
output_path = '/content/drive/MyDrive/Real_data/real_data_2.csv'
df_survey_2.to_csv(output_path, index=False)
print(f"DataFrame saved to: {output_path}")

In [2]:
df_survey_3 = load_with_rater("/content/drive/MyDrive/Real_data/Survey 3 Raw Data.xlsx")
df_survey_3.head()

,Rater,Wellbeing,Team Access,Productivity,Unnamed: 4,<b>Capacity</b> of the team,<b>Capability</b> of the team,<b>Priorities</b> of the team,<b>Collaboration</b> within the team,Ability to challenge decisions and actions <b>safely</b>,...,How well our <b>solution</b> meets the objectives of the challenge,How innovative are we being in our use of <b>technology</b>,How <b>ambitious</b> are we with our solution,What is the <b>commercial application</b> of our solution,How <b>beneficial</b> is our solution,Unnamed: 18,Unnamed: 19,Unnamed: 20,team,person
0,-1100000,46,50,83,NaN,38,42,46,50,54,...,42,46,50,54,58,NaN,Good,Good,11,0
1,-2600004,33,75,19,NaN,25,13,82,82,19,...,67,25,19,78,44,NaN,NaN,NaN,26,4
2,-100003,85,70,59,NaN,71,93,46,59,80,...,79,74,93,52,68,NaN,NaN,NaN,1,3
3,-2700005,66,67,71,NaN,55,60,58,66,68,...,59,60,64,70,72,NaN,NaN,NaN,27,5
4,-200000,80,68,60,NaN,64,71,76,81,85,...,81,71,52,66,71,NaN,NaN,NaN,2,0

In [3]:
output_path = '/content/drive/MyDrive/Real_data/real_data_3.csv'
df_survey_3.to_csv(output_path, index=False)
print(f"DataFrame saved to: {output_path}")

DataFrame saved to: /content/drive/MyDrive/Real_data/real_data_3.csv

In [3]:
df_survey_4 = load_with_rater("/content/drive/MyDrive/Real_data/Survey 4 Raw Data.xlsx")
df_survey_4.head()

,Rater,Wellbeing,Team Access,Productivity,Unnamed: 4,<b>Capacity</b> of the team,<b>Capability</b> of the team,<b>Priorities</b> of the team,<b>Collaboration</b> within the team,Ability to challenge decisions and actions <b>safely</b>,...,How well have we <b>presented </b>our solution,Unnamed: 19,HCD helped me to contribute more,HCD helped our team understand how we were really working together,The insights from the HCD influenced the way our team approached the challenge,Unnamed: 23,Unnamed: 24,Unnamed: 25,team,person
0,-1100000,46,80,83,NaN,38,42,46,50,54,...,86,NaN,46,50,80,NaN,Good,Good,11,0
1,-600000,46,50,54,NaN,100,100,100,100,99,...,100,NaN,11,97,84,NaN,Pretty well,NaN,6,0
2,-400005,74,64,54,NaN,50,42,56,53,65,...,71,NaN,49,54,69,NaN,Well,Better role assignments,4,5
3,-100003,76,62,66,NaN,84,91,56,69,54,...,74,NaN,59,62,54,NaN,NaN,NaN,1,3
4,-600003,80,73,61,NaN,78,77,70,72,76,...,72,NaN,69,73,79,NaN,NaN,NaN,6,3

In [4]:
output_path = '/content/drive/MyDrive/Real_data/real_data_4.csv'
df_survey_4.to_csv(output_path, index=False)
print(f"DataFrame saved to: {output_path}")

DataFrame saved to: /content/drive/MyDrive/Real_data/real_data_4.csv